### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by RihaBerry** [sabihoshi/GenshinLyreMidiPlayer#35]
Like the title, after around the third startup, the application no longer opens. I've attempted restarting, I've attempted using both versions, and I've attempted reinstall. None of these have worked.

**Comment by sabihoshi** [comment]
You most likely have a corrupted MIDI file in your history, open Run (`Ctrl` + `R`) and type in `%localappdata%\sabihoshi` and delete the folder in there in order to delete all your data. After that, try again.

**Comment by NekoCyan** [comment]
> You most likely have a corrupted MIDI file in your history, open Run (`Ctrl` + `R`) and type in `%localappdata%\sabihoshi` and delete the folder in there in order to delete all your data. After that, try again.

Are there anyways to avoid it, I don't know much about C# so I can't fix it.
As u said, this issue might come from corrupted MIDI file.
When the Program is still opening, I can add anything about MIDI and play it, but when re-open it again, It will get crash with the following Exception Error.
```
at ModernWpf.Controls.ContentDialog.ThrowAlreadyOpenException()
   at ModernWpf.Controls.ContentDialog.<ShowAsync>d__134.MoveNext()
   at GenshinLyreMidiPlayer.WPF.ModernWPF.Errors.ExceptionHandler.<TryHandleException>d__2.MoveNext() in \GenshinLyreMidiPlayer-main\GenshinLyreMidiPlayer.WPF\ModernWPF\Errors\ExceptionHandler.cs:line 88
   at GenshinLyreMidiPlayer.WPF.ViewModels.PlaylistViewModel.<AddFile>d__56.MoveNext() in \GenshinLyreMidiPlayer-main\GenshinLyreMidiPlayer.WPF\ViewModels\PlaylistViewModel.cs:line 225
   at GenshinLyreMidiPlayer.WPF.ViewModels.PlaylistViewModel.<AddFiles>d__46.MoveNext() in \GenshinLyreMidiPlayer-main\GenshinLyreMidiPlayer.WPF\ViewModels\PlaylistViewModel.cs:line 116
   at GenshinLyreMidiPlayer.WPF.ViewModels.MainWindowViewModel.<OnViewLoaded>d__26.MoveNext() in \GenshinLyreMidiPlayer-main\GenshinLyreMidiPlayer.WPF\ViewModels\MainWindowViewModel.cs:line 104
   at GenshinLyreMidiPlayer.WPF.ViewModels.MainWindowViewModel.<OnViewLoaded>d__26.MoveNext() in \GenshinLyreMidiPlayer-main\GenshinLyreMidiPlayer.WPF\ViewModels\MainWindowViewModel.cs:line 104
```
*Only some MIDI files being like that.*
